### ISSUE TITLE
opencv problem when compiling

### ISSUE THREAD

**Issue by FSetragno** [imistyrain/MRHead#2]
I'm getting these errors when executing` make -j 10`:

```
CMakeFiles/MRCrossPlatform.dir/MRCrossPlatform.cpp.o: In function `testImage()':
MRCrossPlatform.cpp:(.text+0x742): undefined reference to `cv::imread(std::string const&, int)'
MRCrossPlatform.cpp:(.text+0x784): undefined reference to `cv::namedWindow(std::string const&, int)'
MRCrossPlatform.cpp:(.text+0x7d6): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
CMakeFiles/MRCrossPlatform.dir/MRCrossPlatform.cpp.o: In function `testCamera(int)':
MRCrossPlatform.cpp:(.text+0x8ec): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
CMakeFiles/MRCrossPlatform.dir/MRCrossPlatform.cpp.o: In function `testVideo(std::string const&)':
MRCrossPlatform.cpp:(.text+0x954): undefined reference to `cv::VideoCapture::VideoCapture(std::string const&)'
MRCrossPlatform.cpp:(.text+0x9f6): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
MRCrossPlatform.cpp:(.text+0xa5c): undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'

```

These are the outputs of `pkg-config --cflags opencv` and `pkg-config --libs opencv`:

`-I/usr/include/opencv`

`/usr/lib/arm-linux-gnueabihf/libopencv_calib3d.so -lopencv_calib3d /usr/lib/arm-linux-gnueabihf/libopencv_contrib.so -lopencv_contrib /usr/lib/arm-linux-gnueabihf/libopencv_core.so -lopencv_core /usr/lib/arm-linux-gnueabihf/libopencv_features2d.so -lopencv_features2d /usr/lib/arm-linux-gnueabihf/libopencv_flann.so -lopencv_flann /usr/lib/arm-linux-gnueabihf/libopencv_gpu.so -lopencv_gpu /usr/lib/arm-linux-gnueabihf/libopencv_highgui.so -lopencv_highgui /usr/lib/arm-linux-gnueabihf/libopencv_imgproc.so -lopencv_imgproc /usr/lib/arm-linux-gnueabihf/libopencv_legacy.so -lopencv_legacy /usr/lib/arm-linux-gnueabihf/libopencv_ml.so -lopencv_ml /usr/lib/arm-linux-gnueabihf/libopencv_objdetect.so -lopencv_objdetect /usr/lib/arm-linux-gnueabihf/libopencv_ocl.so -lopencv_ocl /usr/lib/arm-linux-gnueabihf/libopencv_photo.so -lopencv_photo /usr/lib/arm-linux-gnueabihf/libopencv_stitching.so -lopencv_stitching /usr/lib/arm-linux-gnueabihf/libopencv_superres.so -lopencv_superres /usr/lib/arm-linux-gnueabihf/libopencv_ts.so -lopencv_ts /usr/lib/arm-linux-gnueabihf/libopencv_video.so -lopencv_video /usr/lib/arm-linux-gnueabihf/libopencv_videostab.so -lopencv_videostab`

**Comment by imistyrain** [comment]
Sorry, I forget to metion that you should use CMake to generate makefile, not the one  I gave here. It is only used to check my code.
The rightway to use it is:
cd MRHead
sudo sh setup.sh
cd MRCrossPlatform
mkdir build
cd build
cmake ..
make -j20

**Comment by FSetragno** [comment]
Still getting the same errors. It could be due to the fact that opencv is installed in another path. Should I edit the makefile in MRCrossPLatform folder, or the generated one?

**Comment by FSetragno** [comment]
I did not modify anything but I'm trying to build on an Odroid with Ubuntu 16.04.5 LTS. The libraries are located in /usr/lib/arm-linux-gnueabihf so maybe I should specify this in the cmake file

**Comment by imistyrain** [comment]
Oh, that's exactly the reason. You should build opencv for arm from source.
